fixing the cleanup and port assigning part

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -111,18 +111,21 @@ jobs:
 
               echo "Active frontend port: $ACTIVE_FRONTEND_PORT"
 
-              if [ "$ACTIVE_FRONTEND_PORT" = "3001" ]; then
-                  OLD_FRONTEND_PORT=3001
-                  OLD_BACKEND_PORT=5001
+              echo "🔍 Detecting available deployment slot..."
 
+              # Choose free slot dynamically
+              if ! docker ps --format '{{.Ports}}' | grep -q '3002->80'; then
                   NEW_FRONTEND_PORT=3002
                   NEW_BACKEND_PORT=5002
-              else
-                  OLD_FRONTEND_PORT=3002
-                  OLD_BACKEND_PORT=5002
 
+                  OLD_FRONTEND_PORT=3001
+                  OLD_BACKEND_PORT=5001
+              else
                   NEW_FRONTEND_PORT=3001
                   NEW_BACKEND_PORT=5001
+
+                  OLD_FRONTEND_PORT=3002
+                  OLD_BACKEND_PORT=5002
               fi
 
               echo "Old Ports → Frontend:$OLD_FRONTEND_PORT Backend:$OLD_BACKEND_PORT"
@@ -130,15 +133,18 @@ jobs:
 
               echo "📦 Deploying to new ports: $NEW_FRONTEND_PORT / $NEW_BACKEND_PORT"
 
-              # Cleanup previous green leftovers
+              # Cleanup previous leftovers
               docker stop frontend-green backend-green || true
               docker rm frontend-green backend-green || true
+
+              docker stop frontend-next backend-next || true
+              docker rm frontend-next backend-next || true
 
               # Run backend
               docker run -d \
                 -p $NEW_BACKEND_PORT:5000 \
                 -e BASE_URL=http://13.233.225.177 \
-                -e SIMULATE_CRASH=true \
+                -e SIMULATE_CRASH=false \
                 --name backend-green \
                 ${{ secrets.DOCKER_USERNAME }}/ushawty-backend:latest
 
